### ISSUE TITLE
Unable to Access Purchased eBook "Cloudflare for Speed and Security" Despite Payment Confirmation

### ISSUE THREAD

**Issue by kimurakoki** [skerkour/cloudflare-for-speed-and-security#8]
Hello,

I have encountered an issue with accessing the eBook "Cloudflare for Speed and Security" that I purchased recently. I have received payment confirmations from both the site and Visa, indicating that the transaction was successful. However, I am unable to access the eBook, and no orders are displayed in my account section.

I have already reached out via email but have not received any response yet. Could you please check on this issue and provide guidance on how I can access my purchased eBook?

Thank you for your assistance.

**Comment by kimurakoki** [comment]
@sylvain101010 please

**Comment by ghost** [comment]
Hi @kimurakoki 

Thank you very much for your support and I'm really sorry for the poor experience.

I was fighting against malicious order(s) and my code to block malicious account had a bug which prevented you to access your account. You can read more in the postmortem: https://kerkour.com/website-outage-april-2024-postmortem

It should be now fixed. Please let me know by email if the problem persists on your side.

**Comment by kimurakoki** [comment]
@sylvain101010 I tried to log in, but as shown in the image, nothing appears in 'orders', and I can't find it.
![sylvain](https://github.com/skerkour/cloudflare-for-speed-and-security/assets/106098990/87a0d8b4-ddda-4177-ad9b-fb1d5710e53d)
